language: android

env:
  global:
    - COMPILE_SDK_VERSION=27 # Same as `compileSdkVersion` in build.gradle
    - EMULATOR_API=26
    - ABI=armeabi-v7a
    - TAG=google_apis
    - ADB_INSTALL_TIMEOUT=5 # minutes

android:
  components:
    - tools # Update android-sdk (also called android-sdk-tools)
    - platform-tools
    - tools # Write the second time to update to thes newest as described in the document
    - build-tools-${BUILD_TOOLS_VERSION} # For building
    - android-${COMPILE_SDK_VERSION} # For building
    - android-${EMULATOR_API} # For testing
    - extra-android-m2repository # Support library
    - sys-img-${ABI}-${TAG}-${EMULATOR_API} 

notifications:
  email: false

before_install:
  - yes | sdkmanager "platforms;android-27"

before_script:
  - echo no | android create avd --force -n test -t "android-${EMULATOR_API}" --abi ${ABI} --tag ${TAG}
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew assembleDebug